# The Climate is Changing: How is the Research?

## Exploring Trends in Climate Articles: 2013 to 2023

#### This notebook explores BOW and TFIDF concepts within the corpus.

#### Written by Rafael Alvarado(1) and Caroline Kranefuss(1).

(1) University of Virginia, 2026

### Imports

In [42]:
# General imports
import pandas as pd 
import numpy as np 
from numpy.linalg import norm
import os
import sys

# Plotting
import plotly.express as px

# Project-specific imports
import glob
from lxml import etree
from glob import glob
import re
import nltk
nltk_resources = [
    'tokenizers/punkt', 
    'averaged_perceptron_tagger_eng',
    'corpora/stopwords', 
    'help/tagsets'
]

for resource in nltk_resources:
    try:
        nltk.data.find(resource)
    except LookupError:
        nltk.download(resource)
        
        
# ----File Stitching----
# If not in repo home folder, cd back 
if os.path.basename(os.getcwd()) != "evolving_sentiment_climate":
    os.chdir('..')
# If a file is in /sources/, access it by telling the system to look at that path as well as current path
sys.path.append(os.path.join(os.getcwd(), 'sources'))
source_dir = "sources"
source_files_paths = glob(f"{source_dir}/*.xml")
# Same for csvs
sys.path.append(os.path.join(os.getcwd(), 'csvs'))
csvs_dir = "csvs"
csvs_files_paths = glob(f"{csvs_dir}/*.csv")

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [3]:
DOCS = pd.read_csv("csvs/DOC/DOC.csv")

In [4]:
%%capture
%run notebooks/LDA.ipynb

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [9]:
%%capture
%run notebooks/PCA.ipynb

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [10]:
THETA.T

doc_id,0,1,2,3,4,5,6,7,8,9,...,82,83,84,85,86,87,88,89,90,91
topic_id,,,,,,,,,,,,,,,,,,,,,
T00,0.000035,0.800089,0.405469,0.000029,0.078766,0.000020,0.067770,0.000028,0.109841,0.146497,...,0.151501,0.000031,0.238063,0.048024,0.071592,0.000020,0.000019,0.000019,0.057597,0.000032
T01,0.000035,0.000017,0.000033,0.000029,0.026688,0.000020,0.000040,0.000028,0.000047,0.052811,...,0.000009,0.000031,0.264554,0.047474,0.111026,0.039702,0.000019,0.000019,0.000024,0.000032
T02,0.000035,0.000017,0.000033,0.000029,0.000058,0.525239,0.557570,0.000028,0.000047,0.000038,...,0.000009,0.118096,0.000032,0.014848,0.053080,0.000020,0.929027,0.000019,0.000024,0.000032
T03,0.000035,0.000017,0.046923,0.000029,0.000058,0.000020,0.151709,0.000028,0.000047,0.000038,...,0.000009,0.000031,0.000032,0.032652,0.032358,0.742740,0.000019,0.000019,0.000024,0.000032
T04,0.000035,0.000017,0.000033,0.000029,0.000058,0.308759,0.000040,0.000028,0.000047,0.000038,...,0.000009,0.000031,0.000032,0.000054,0.000035,0.000020,0.000019,0.000019,0.034826,0.000032
T05,0.000035,0.000017,0.018897,0.000029,0.363233,0.000020,0.000040,0.000028,0.000047,0.027214,...,0.004451,0.000031,0.000032,0.000054,0.000035,0.000020,0.000019,0.000019,0.000024,0.000032
T06,0.000035,0.000017,0.242604,0.999442,0.000058,0.000020,0.000040,0.000028,0.000047,0.000038,...,0.000009,0.236406,0.000032,0.031045,0.398313,0.000020,0.000019,0.000019,0.000024,0.000032
T07,0.000035,0.000017,0.000033,0.000029,0.062378,0.000020,0.034567,0.000028,0.051059,0.064969,...,0.157966,0.000031,0.000032,0.000054,0.000035,0.000020,0.000019,0.000019,0.000024,0.000032
T08,0.000035,0.000017,0.000033,0.000029,0.151982,0.000020,0.023468,0.000028,0.000047,0.000038,...,0.000009,0.000031,0.000032,0.000054,0.158223,0.058523,0.000019,0.000019,0.045960,0.000032
T09,0.000035,0.000017,0.000033,0.000029,0.000058,0.000020,0.000040,0.000028,0.047036,0.000038,...,0.000009,0.000031,0.016051,0.000054,0.000035,0.000020,0.000019,0.000019,0.029582,0.746040
T10,0.999328,0.000017,0.000033,0.000029,0.000058,0.000020,0.008779,0.000028,0.000047,0.000038,...,0.000009,0.000031,0.000032,0.000054,0.000035,0.000020,0.000019,0.000019,0.000024,0.000032
T11,0.000035,0.000017,0.000033,0.000029,0.000058,0.000020,0.000040,0.000028,0.011286,0.000038,...,0.000009,0.000031,0.153899,0.452547,0.000035,0.000020,0.000019,0.000019,0.157225,0.000032
T12,0.000035,0.012249,0.000033,0.000029,0.000058,0.015225,0.000040,0.000028,0.021882,0.358791,...,0.000009,0.058722,0.261692,0.000054,0.000035,0.040749,0.000019,0.999634,0.000024,0.000032
T13,0.000035,0.187379,0.263749,0.000029,0.010812,0.000020,0.000040,0.000028,0.000047,0.000038,...,0.035077,0.197000,0.000032,0.372706,0.000035,0.000020,0.000019,0.000019,0.000024,0.000032
T14,0.000035,0.000017,0.000033,0.000029,0.000058,0.000020,0.020985,0.000028,0.000047,0.000038,...,0.000009,0.000031,0.027169,0.000054,0.022721,0.000020,0.000019,0.000019,0.004702,0.000032
T15,0.000035,0.000017,0.021895,0.000029,0.039731,0.000020,0.000040,0.000028,0.576902,0.095874,...,0.562392,0.389311,0.000032,0.000054,0.000035,0.000020,0.000019,0.000019,0.000024,0.094420
T16,0.000035,0.000017,0.000033,0.000029,0.000058,0.000020,0.000040,0.000028,0.014139,0.000038,...,0.000009,0.000031,0.038159,0.000054,0.000035,0.000020,0.070626,0.000019,0.065769,0.158991
T17,0.000035,0.000017,0.000033,0.000029,0.208407,0.000020,0.000040,0.999466,0.000047,0.000038,...,0.000009,0.000031,0.000032,0.000054,0.152267,0.000020,0.000019,0.000019,0.589424,0.000032
T18,0.000035,0.000017,0.000033,0.000029,0.057362,0.150460,0.008460,0.000028,0.000047,0.000038,...,0.031960,0.000031,0.000032,0.000054,0.000035,0.117983,0.000019,0.000019,0.014653,0.000032
T19,0.000035,0.000017,0.000033,0.000029,0.000058,0.000020,0.126257,0.000028,0.167290,0.253352,...,0.056531,0.000031,0.000032,0.000054,0.000035,0.000020,0.000019,0.000019,0.000024,0.000032

In [31]:
# Define engine
pca_engine = PCA(n_components=3)
# Run engine on the TRANSPOSE of THETA
engine_run = pca_engine.fit_transform(THETA.T)
# Define index
index_TCM = THETA.T.index
# Turn into df
TCM = pd.DataFrame(engine_run, index=index_TCM)
TCM.rename(columns={0:'PC0', 1:'PC1', 2:'PC2'}, inplace=True)
# View
TCM

               PC0       PC1       PC2
topic_id
T00       0.266906  1.561636 -0.824607
T01      -0.053559  0.042892 -0.020499
T02       0.209107 -0.452577 -0.701888
T03      -0.137704 -0.032044 -0.301019
T04      -0.120279 -0.144961 -0.071809
T05      -0.204895 -0.088653 -0.064404
T06      -0.214561 -0.017499  0.120689
T07      -0.081277 -0.253162 -0.182709
T08      -0.263397 -0.291939 -0.229332
T09      -0.196194 -0.263687  0.045162
T10       0.015192 -0.193468 -0.036048
T11       0.021507  0.159005  0.446412
T12       0.006934 -0.051907 -0.083263
T13      -0.384219  0.730292  1.208653
T14      -0.076326 -0.114969 -0.065682
T15       0.253157 -0.006096  0.182946
T16      -0.331389 -0.292060  0.270058
T17      -0.452498  0.087949  0.013913
T18      -0.169793 -0.205497 -0.096462
T19       1.913288 -0.173257  0.389891

In [38]:
# Make a components table that essentially documents the explained variance of each term
# I.e., how much each term is part of any given component
# This will help in defining the components' meanings 
COMPS = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
# Formatting and settings (columns, index, transpose for easy viewing)
COMPS.columns = ["PC{}".format(i) for i in COMPS.columns]
COMPS.index = THETA.T.columns
# COMPS.index.name = 'term_str'
COMPS

             PC0       PC1       PC2
doc_id
0       0.001628 -0.023147 -0.004538
1       0.015190  0.165895 -0.054715
2      -0.005356  0.097958  0.000297
3      -0.022997 -0.002094  0.015196
4      -0.021235  0.005494 -0.014795
...          ...       ...       ...
87     -0.014967 -0.007846 -0.031820
88      0.018324 -0.052808 -0.079745
89      0.000743 -0.006212 -0.010486
90     -0.031601  0.014097  0.004440
91     -0.018783 -0.029179  0.011828

[92 rows x 3 columns]

In [43]:
# Adapting plotting functions
# A function to visualize the principal components
# Inputs: The DCM df, PCs a and b
def vis_pcs(DCM, a, b):
    return px.scatter(DCM, f"PC{a}", f"PC{b}", 
                      hover_name=DCM.index.get_level_values('topic_id').astype(str),
                      marginal_x='box', height=800)

# Another function for visualization
# Inputs: The COMPS df, PCs and b
def vis_loadings(COMPS, a, b):
    return px.scatter(COMPS, f"PC{a}", f"PC{b}", 
                      text=COMPS.index,
                      hover_name=COMPS.index,
                      marginal_x='box', 
                      height=800)

In [44]:
vis_pcs(TCM, 0, 1)

In [41]:
vis_loadings(COMPS, 0,1)