# The Climate is Changing: How is the Research?

## Exploring Trends in Climate Articles: 2013 to 2023

#### This notebook explores BOW and TFIDF concepts within the corpus.

#### Written by Rafael Alvarado(1) and Caroline Kranefuss(1).

(1) University of Virginia, 2026

### Imports

In [2]:
# General imports
import pandas as pd 
import numpy as np 
from numpy.linalg import norm
import os
import sys

# Plotting
import matplotlib.pyplot as plt
import seaborn as sns

# Project-specific imports
import glob
from lxml import etree
from glob import glob
import re
import nltk
nltk_resources = [
    'tokenizers/punkt', 
    'averaged_perceptron_tagger_eng',
    'corpora/stopwords', 
    'help/tagsets'
]

for resource in nltk_resources:
    try:
        nltk.data.find(resource)
    except LookupError:
        nltk.download(resource)
        
        
# ----File Stitching----
# If not in repo home folder, cd back 
if os.path.basename(os.getcwd()) != "evolving_sentiment_climate":
    os.chdir('..')
# If a file is in /sources/, access it by telling the system to look at that path as well as current path
sys.path.append(os.path.join(os.getcwd(), 'sources'))
source_dir = "sources"
source_files_paths = glob(f"{source_dir}/*.xml")
# Same for csvs
sys.path.append(os.path.join(os.getcwd(), 'csvs'))
csvs_dir = "csvs"
csvs_files_paths = glob(f"{csvs_dir}/*.csv")

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [3]:
DOCS = pd.read_csv("csvs/DOC/DOC.csv")

In [4]:
%%capture
%run notebooks/LDA.ipynb

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [ ]:
%%capture
%run notebooks/PCA.ipynb

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [11]:
THETA.T

doc_id,0,1,2,3,4,5,6,7,8,9,...,82,83,84,85,86,87,88,89,90,91
topic_id,,,,,,,,,,,,,,,,,,,,,
T00,0.123592,0.000017,0.036449,0.000029,0.000058,0.000020,0.000040,0.999466,0.059516,0.187837,...,0.000009,0.083679,0.122631,0.000054,0.413250,0.050015,0.000019,0.000019,0.000024,0.000032
T01,0.031978,0.000017,0.014697,0.000029,0.000058,0.000020,0.000040,0.000028,0.259475,0.107564,...,0.000009,0.000031,0.000032,0.000054,0.000035,0.013319,0.000019,0.000019,0.000024,0.046891
T02,0.000035,0.000017,0.000033,0.000029,0.000058,0.101473,0.052714,0.000028,0.000047,0.000038,...,0.000009,0.041170,0.000032,0.000054,0.187523,0.000020,0.890227,0.000019,0.183760,0.000032
T03,0.000035,0.000017,0.014707,0.000029,0.000058,0.000020,0.000040,0.000028,0.264855,0.079176,...,0.999821,0.202570,0.000032,0.000054,0.042243,0.000020,0.000019,0.000019,0.000024,0.000032
T04,0.000035,0.000017,0.000033,0.000029,0.000058,0.058124,0.340751,0.000028,0.000047,0.000038,...,0.000009,0.082628,0.000032,0.000054,0.000035,0.000020,0.000019,0.000019,0.000024,0.000032
T05,0.000035,0.000017,0.000033,0.000029,0.000058,0.076452,0.024969,0.000028,0.000047,0.000038,...,0.000009,0.000031,0.000032,0.000054,0.021682,0.127999,0.000019,0.000019,0.000024,0.000032
T06,0.082893,0.000017,0.000033,0.000029,0.000058,0.007197,0.042096,0.000028,0.008588,0.042568,...,0.000009,0.042819,0.029587,0.000054,0.032908,0.003504,0.000019,0.000019,0.000024,0.000032
T07,0.000035,0.999683,0.569481,0.000029,0.000058,0.000020,0.000040,0.000028,0.009128,0.000038,...,0.000009,0.130025,0.079384,0.015031,0.072343,0.007165,0.009681,0.000019,0.000024,0.273061
T08,0.000035,0.000017,0.005863,0.000029,0.104063,0.000020,0.000040,0.000028,0.000047,0.000038,...,0.000009,0.000031,0.000032,0.000054,0.029476,0.000020,0.000019,0.000019,0.000024,0.000032
T09,0.000035,0.000017,0.019871,0.000029,0.000058,0.028016,0.003568,0.000028,0.000047,0.000038,...,0.000009,0.000031,0.000032,0.000054,0.073476,0.137615,0.000019,0.000019,0.028351,0.000032
T10,0.000035,0.000017,0.000033,0.000029,0.000058,0.021650,0.000040,0.000028,0.000047,0.000038,...,0.000009,0.027531,0.000032,0.446190,0.000035,0.028659,0.000019,0.999634,0.000024,0.000032
T11,0.000035,0.000017,0.088585,0.737312,0.000058,0.000020,0.188998,0.000028,0.057582,0.147421,...,0.000009,0.000031,0.049950,0.160136,0.126716,0.099490,0.000019,0.000019,0.000024,0.000032
T12,0.427726,0.000017,0.000033,0.000029,0.000058,0.000020,0.013057,0.000028,0.096892,0.054299,...,0.000009,0.000031,0.026043,0.000054,0.000035,0.000020,0.000019,0.000019,0.000024,0.077782
T13,0.000035,0.000017,0.141650,0.000029,0.000058,0.000020,0.000040,0.000028,0.000047,0.000038,...,0.000009,0.123222,0.000032,0.297495,0.000035,0.000020,0.000019,0.000019,0.000024,0.185329
T14,0.000035,0.000017,0.000033,0.262160,0.000058,0.000020,0.000040,0.000028,0.100990,0.000038,...,0.000009,0.047524,0.000032,0.000054,0.000035,0.000020,0.000019,0.000019,0.000024,0.340565
T15,0.000035,0.000017,0.051137,0.000029,0.775549,0.000020,0.008353,0.000028,0.000047,0.257808,...,0.000009,0.000031,0.454142,0.000054,0.000035,0.059925,0.000019,0.000019,0.787481,0.000032
T16,0.000035,0.000017,0.024791,0.000029,0.000058,0.000020,0.000040,0.000028,0.000047,0.021779,...,0.000009,0.064056,0.000032,0.000054,0.000035,0.000020,0.000019,0.000019,0.000024,0.000032
T17,0.000035,0.000017,0.009834,0.000029,0.000058,0.000020,0.000040,0.000028,0.017853,0.010999,...,0.000009,0.154497,0.000032,0.000054,0.000035,0.000020,0.012194,0.000019,0.000024,0.051999
T18,0.333281,0.000017,0.022670,0.000029,0.000058,0.000020,0.300676,0.000028,0.095484,0.090169,...,0.000009,0.000031,0.237850,0.080336,0.000035,0.472107,0.000019,0.000019,0.000024,0.000032
T19,0.000035,0.000017,0.000033,0.000029,0.119396,0.706831,0.024423,0.000028,0.029213,0.000038,...,0.000009,0.000031,0.000032,0.000054,0.000035,0.000020,0.087590,0.000019,0.000024,0.023952

In [14]:
# Define engine
pca_engine = PCA(n_components=3)
# Run engine on the TRANSPOSE of THETA
engine_run = pca_engine.fit_transform(THETA.T)
# Define index
index_TCM = THETA.T.index
# Turn into df
TCM = pd.DataFrame(engine_run, index=index_TCM)
# View
TCM

                 0         1         2
topic_id
T00      -0.175484 -0.054724 -0.356639
T01      -0.050977 -0.142965 -0.272877
T02       0.024185 -0.177632  0.091866
T03      -0.140667 -0.100122  0.101426
T04      -0.253415  0.201863 -0.178111
T05      -0.067799 -0.210772 -0.095025
T06      -0.200553 -0.023861 -0.171447
T07       0.117799 -0.195711  0.012109
T08      -0.026639 -0.267011 -0.106892
T09       0.026272 -0.242106 -0.124702
T10       0.049717 -0.157639 -0.027105
T11      -0.263942  0.244741  0.879656
T12      -0.188247  0.006505 -0.339953
T13       2.046412  0.725733 -0.013833
T14       0.111060 -0.224490 -0.054735
T15      -0.136872  0.055071  1.198937
T16      -0.069858 -0.470678 -0.323650
T17       0.041451 -0.266060 -0.186224
T18      -0.799263  1.741925 -0.264923
T19      -0.043179 -0.442068  0.232123